### ISSUE TITLE
Change tracing example to use OpenTelemetry SDK

### ISSUE THREAD

**Issue by artursouza** [dapr/python-sdk#487]
## Describe the proposal

Current example for tracing uses OpenCensus SDK: https://github.com/dapr/python-sdk/blob/master/examples/w3c-tracing/invoke-caller.py

OpenTelemetry is the new industry standard. We should use that instead: https://opentelemetry.io/docs/instrumentation/python/cookbook/#manually-setting-span-context

**Comment by berndverst** [comment]
https://opentelemetry-python.readthedocs.io/en/latest/exporter/zipkin/zipkin.html

Probably need:
```
opentelemetry-sdk==1.14.0
opentelemetry-api==1.14.0
opentelemetry-exporter-zipkin==1.14.0
```

But couldn't immediately figure out how to set up the same sampling etc

Would be great if someone with OpenTelemetry experience could take a look here.

**Comment by berndverst** [comment]
Using this guide https://logz.io/blog/python-opentelemetry-auto-instrumentation/#run

Combined with the following config (to use the zipkin exporter) helps to get started with a local dev setup:

```yaml
receivers:  
  otlp:
    protocols:
      grpc:
      http:

exporters:
  zipkin:
    endpoint: "localhost:9411"

processors:
  batch:

extensions:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679
  health_check:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin]
```
